### PR TITLE
middleware no longer increments retry_count

### PR DESCRIPTION
**Pull request by marcvis**
https://thinkneardev.atlassian.net/browse/ES-3036

### CODE REVIEW

**Comment by nselvakkumaran** [comment]
lol

**Comment by eduardog** [comment]
would you mind updating the spec(s) for 'on last attempt' to better fit the real behavior?  I see at least one that feeds in `{retry: 5, retry_count: 5}`, but this middleware will never see the `retry_count` after Sidekiq has incremented for the current failure.

**Comment by eduardog** [comment]
Just 1 comment

**Comment by marcvis** [comment]
Will do.  Updating now

**Comment by marcvis** [comment]
Updated

**Pull request merged**
